# Generated by Django 3.1.1 on 2020-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ManyToManyField(to='model_learn.Product')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
